# For more options:
# https://github.com/cypress-io/github-action

name: 'dhis2-cypress test'

on:
    push:
        branches:
            - master
    pull_request:

env:
    SERVER_START_CMD: 'custom-start-command'
    SERVER_URL: 'custom-url'
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
    e2e:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        strategy:
            matrix:
                containers: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Tests
              uses: cypress-io/github-action@v1
              with:
                  record: true
                  parallel: true
                  start: ${{ env.SERVER_START_CMD }}
                  wait-on: ${{ env.SERVER_URL }}
                  wait-on-timeout: 60
                  group: 'e2e'
              env:
                  CI: true
                  STORYBOOK_TESTING: true
