name: "DHIS2: Lint"

on: pull_request

jobs:
    pr:
        name: Code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Lint
              run: |
                  npx d2-style js check
                  npx d2-style text check
