name: 'dhis2: test (node)'

on: push

jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Test
              run: yarn test
        env:
            CI: true
